
# Site settings
title: 
email: 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://softtwilight.github.io/" # the base hostname & protocol for your site

markdown: kramdown
future: true
# toc_levels: 1……2

# paginate: 10
# paginate_path: ":num"

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - blog pull and debug.bat
